/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for ASCII art conversion. */
export interface ConvertOptionsJs {
  /** Output mode: "ascii", "half-block", or "braille" */
  mode?: string
  /** Output width in characters */
  width?: number
  /** Output height in characters */
  height?: number
  /** Invert brightness */
  invert?: boolean
  /** Custom ASCII character ramp (ascii mode only) */
  charset?: string
}
/** Convert an image file to ASCII art. */
export declare function convert(path: string, options?: ConvertOptionsJs | undefined | null): string
/** Convert in-memory image bytes to ASCII art. */
export declare function convertBytes(data: Buffer, options?: ConvertOptionsJs | undefined | null): string
/** Reusable converter with preset options. */
export declare class Converter {
  constructor(options?: ConvertOptionsJs | undefined | null)
  /** Convert an image file to ASCII art string. */
  convert(path: string): string
  /** Convert in-memory image bytes to ASCII art string. */
  convertBytes(data: Buffer): string
}
