/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for ASCII art conversion. */
export interface ConvertOptionsJs {
  /** Output mode: "ascii", "half-block", or "braille" */
  mode?: string
  /** Output width in characters */
  width?: number
  /** Output height in characters */
  height?: number
  /** Invert brightness */
  invert?: boolean
  /** Custom ASCII character ramp (ascii mode only) */
  charset?: string
}
/** Convert an image file to ASCII art. */
export declare function convert(path: string, options?: ConvertOptionsJs | undefined | null): string
/** Convert in-memory image bytes to ASCII art. */
export declare function convertBytes(data: Buffer, options?: ConvertOptionsJs | undefined | null): string
/**
 * Decode all audio from a video file and play it back in a background thread.
 * Returns immediately; audio continues playing in the background.
 */
export declare function playAudioAsync(path: string): void
/** Reusable converter with preset options. */
export declare class Converter {
  constructor(options?: ConvertOptionsJs | undefined | null)
  /** Convert an image file to ASCII art string. */
  convert(path: string): string
  /** Convert in-memory image bytes to ASCII art string. */
  convertBytes(data: Buffer): string
}
/** Iterator over video frames converted to ASCII art strings. */
export declare class VideoFrames {
  /** Open a video file for frame-by-frame ASCII conversion. */
  constructor(path: string, options?: ConvertOptionsJs | undefined | null)
  /** Frames per second of the video. */
  get fps(): number
  /** Get the next frame as an ASCII art string, or null when done. */
  nextFrame(): string | null
}
